### ISSUE TITLE
Problem: installation instructions

### ISSUE THREAD

**Issue by jorikvankemenade** [artefactual/automation-tools#114]
When using the installation instructions for using the automation tools with a docker install I ran into a few problems. I think these are more general problems of the installation instructions and I think it might be a good idea to update the instructions. Before doing that I would like to know if you agree.

Proposed changes:
1. Add `sudo` to the commands for creating the automation directories. All parent directories are owned by root, not the user.
2. Add instructions for creating the `archivematica` group and user. In my case they didn't exist - but this might be because of the docker installation.
3. Add instrcutions for changing ownership of the new directories from root to the user.

If you think that this is a good idea I'll go ahead and create a PR for changing this.

**Comment by ross-spencer** [comment]
Hi @jorikvankemenade thanks for logging this! I've moved the issue over to our primary issues repo to track it better. Will comment there.
