### ISSUE TITLE
Problem: fits:fslastmodified is not always available as a source for setting the modified date of DIP files

### ISSUE THREAD

**Issue by ehanson8** [artefactual/automation-tools#147]
DIPs produced using `automation-tools` are supposed to re-write the last modified dates to files to what is recorded in the PREMIS metadata during Archivematica processing. However, this currently relies on last modified dates extracted by `fits`, which does not run reliably on all files and causes the modified date re-write to fail during DIP creation without this data present.

Given that `fits` elements are not always present in AIPs’ PREMIS metadata, the PREMIS element `dateCreatedByApplication` could be a preferable source for setting the modified date of DIP files produced with `automation-tools`.

If using `dateCreatedByApplication` is a desirable solution, I have a small fix to address this issue and can open up a PR for review in a fork.

**Comment by eviau-artefactual** [comment]
Hi @ehanson8 !

I don't think we document it somewhere, so it's okay if this comes as a surprise : would it be possible to rephrase the issue with the problem stated in the title? Something like : `Problem: ...` would help us gain a better understanding of why the change might be needed.

This project currently follows [Archivematica contributing guidelines](https://github.com/artefactual/archivematica/blob/qa/1.x/CONTRIBUTING.md), for your information.

If you have a PR to submit, feel welcome to do so - note that you will have to [sign a CLA](https://github.com/artefactual/archivematica/blob/qa/1.x/CONTRIBUTING.md#contributors-agreement).

Let us know if you have questions!

**Comment by ehanson8** [comment]
Thanks for the guidance @eviau-artefactual, I updated the issue as requested and submitted the contributor's agreement. If there's interest, I'll open a PR for this [commit](https://github.com/artefactual/automation-tools/compare/master...MITLibraries:automation-tools:datecreatedbyapplication)

**Comment by jfcarrano** [comment]
@eviau-artefactual is there anything else you need Eric or I to do? Should he go ahead and submit a PR?

**Comment by joel-simpson** [comment]
@ehanson8 since you signed the contributors agreement then please go ahead and submit a PR for this... we'd love to include it.
