### ISSUE TITLE
Problem: transfers/amclient.py is not documented in the README

### ISSUE THREAD

**Issue by hakamine** [artefactual/automation-tools#32]
`transfers/amclient.py` is a nice module and CLI that holds functionality for interacting with the various Archivematica APIs (for example, it can be used to automate hiding of completed transfers/ingests in the dashboard). The repository's README does not mention it, it would be a good thing to add information about it there (`amclient.py`'s source code has docstrings that could be used for this purpose)

**Comment by ross-spencer** [comment]
Closed initially by e6b6fc9

Additional documentation for the most recently added functions can be found in the AMClient section of the README.md https://github.com/artefactual/automation-tools#archivematica-client
