### ISSUE TITLE
Problem: this repo has no contributing.md

### ISSUE THREAD

**Issue by sromkey** [artefactual/automation-tools#90]
Would it be worthwhile to have a contributing.md for this repo? Questions to consider are how issues are filed in the Archivematica vs. AtoM vs. Binder projects and whether we want this repo to follow the same pattern?

**Comment by eviau-artefactual** [comment]
I believe this issue was closed by https://github.com/artefactual/automation-tools/pull/144 - let me know if that is not the case by re-opening this issue.
